# Livro para consulta:
- https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html
- https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html

# 1. Importando bibliotecas <a name="import"></a>

<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

# 2. Carregando o dataframe SINASC <a name="read"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [4]:
sinasc_raw = pd.read_csv('SINASC_RO_2019.csv')
sinasc_raw.head()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,1,2679477.0,110001,1,19,5.0,8 a 11 anos,NaN,0.0,0.0,...,5,1,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
1,1,2679477.0,110001,1,29,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,2,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
2,1,2679477.0,110001,1,37,9.0,8 a 11 anos,513205.0,2.0,0.0,...,5,3,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025

In [19]:
sinasc_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27028 entries, 0 to 27027
Data columns (total 69 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ORIGEM        27028 non-null  int64
 1   CODESTAB      26913 non-null  float64
 2   CODMUNNASC    27028 non-null  int64
 3   LOCNASC       27028 non-null  int64
 4   IDADEMAE      27028 non-null  int64
 5   ESTCIVMAE     26711 non-null  float64
 6   ESCMAE        26716 non-null  object
 7   CODOCUPMAE    24121 non-null  float64
 8   QTDFILVIVO    25455 non-null  float64
 9   QTDFILMORT    24930 non-null  float64
 10  CODMUNRES     27028 non-null  int64
 11  GESTACAO      25796 non-null  object
 12  GRAVIDEZ      26949 non-null  object
 13  PARTO         26979 non-null  object
 14  CONSULTAS     27028 non-null  int64
 15  DTNASC        27028 non-null  object
 16  HORANASC      27007 non-null  float64
 17  SEXO          27024 non-null  object
 18  APGAR1        26932 non-null  float64
 19  APGAR5        26925 non-null  float64
 20  RACACOR       26381 non-null  object
 21  PESO          27028 non-null  int64
 22  IDANOMAL      26437 non-null  float64
 23  DTCADASTRO    27028 non-null  object
 24  CODANOMAL     214 non-null    object
 25  NUMEROLOTE    27028 non-null  int64
 26  VERSAOSIST    27028 non-null  object
 27  DTRECEBIM     27028 non-null  object
 28  DIFDATA       27028 non-null  int64
 29  DTRECORIGA    0 non-null      float64
 30  NATURALMAE    26730 non-null  float64
 31  CODMUNNATU    26730 non-null  float64
 32  CODUFNATU     26730 non-null  float64
 33  ESCMAE2010    26779 non-null  float64
 34  SERIESCMAE    14318 non-null  float64
 35  DTNASCMAE     26988 non-null  float64
 36  RACACORMAE    26367 non-null  float64
 37  QTDGESTANT    25816 non-null  float64
 38  QTDPARTNOR    25149 non-null  float64
 39  QTDPARTCES    25237 non-null  float64
 40  IDADEPAI      7607 non-null   float64
 41  DTULTMENST    16956 non-null  float64
 42  SEMAGESTAC    25790 non-null  float64
 43  TPMETESTIM    25790 non-null  float64
 44  CONSPRENAT    26098 non-null  float64
 45  MESPRENAT     24161 non-null  float64
 46  TPAPRESENT    26763 non-null  float64
 47  STTRABPART    26081 non-null  float64
 48  STCESPARTO    26281 non-null  float64
 49  TPNASCASSI    26967 non-null  float64
 50  TPFUNCRESP    26961 non-null  float64
 51  TPDOCRESP     27014 non-null  float64
 52  DTDECLARAC    26976 non-null  float64
 53  ESCMAEAGR1    26779 non-null  float64
 54  STDNEPIDEM    27028 non-null  int64
 55  STDNNOVA      27028 non-null  int64
 56  CODPAISRES    27028 non-null  int64
 57  TPROBSON      27028 non-null  int64
 58  PARIDADE      27028 non-null  int64
 59  KOTELCHUCK    27028 non-null  int64
 60  CONTADOR      27028 non-null  int64
 61  munResStatus  27028 non-null  object
 62  munResTipo    27028 non-null  object
 63  munResNome    27028 non-null  object
 64  munResUf      27028 non-null  object
 65  munResLat     27027 non-null  float64
 66  munResLon     27027 non-null  float64
 67  munResAlt     27027 non-null  float64
 68  munResArea    27027 non-null  float64
dtypes: float64(38), int64(16), object(15)
memory usage: 14.2+ MB

# Tarefa 1

### 1. Idade media das mães e dos pais por município (coluna munResNome)

In [17]:
sinasc_raw.groupby('munResNome').agg({'IDADEMAE': 'mean', 'IDADEPAI': 'mean'})

                            IDADEMAE   IDADEPAI
munResNome
Alta Floresta D'Oeste      25.991826  29.548701
Alto Alegre dos Parecis    24.844156  29.179104
Alto Paraíso               24.960177  28.833333
Alvorada D'Oeste           25.770732  30.757282
Ariquemes                  25.607866  32.466667
Buritis                    25.559177  30.812500
Cabixi                     26.037500  34.333333
Cacaulândia                25.546667  36.333333
Cacoal                     26.890102  30.931854
Campo Novo de Rondônia     24.825301  30.500000
Candeias do Jamari         25.243323  29.894737
Castanheiras               27.281250  30.392857
Cerejeiras                 27.240506  31.652778
Chupinguaia                25.333333  29.629630
Colorado do Oeste          27.602804  34.354839
Corumbiara                 24.716535  32.470588
Costa Marques              24.412017  30.613636
Cujubim                    24.482927  31.400000
Espigão D'Oeste            26.093333  31.198113
Governador Jorge Teixeira  24.401786  29.222222
Guajará-Mirim              25.462228  30.470588
Itapuã do Oeste            26.064220  42.500000
Jaru                       25.982974  32.197183
Ji-Paraná                  26.361137  31.132239
Machadinho D'Oeste         25.480000  31.326923
Ministro Andreazza         27.904762  33.849315
Mirante da Serra           26.304878  32.154762
Monte Negro                25.648241  34.678571
Município ignorado - RO    24.000000  22.000000
Nova Brasilândia D'Oeste   26.222222  30.520833
Nova Mamoré                25.326389  31.692308
Nova União                 26.894231  31.371429
Novo Horizonte do Oeste    26.938776  31.588235
Ouro Preto do Oeste        26.375594  31.233244
Parecis                    26.454545  32.473684
Pimenta Bueno              25.199675  29.745174
Pimenteiras do Oeste       25.075000  35.600000
Porto Velho                26.312670  32.352679
Presidente Médici          25.796053  30.150754
Primavera de Rondônia      27.023256  31.888889
Rio Crespo                 26.660000  28.000000
Rolim de Moura             26.600863  30.360479
Santa Luzia D'Oeste        26.121212  30.703297
Seringueiras               24.910714  30.500000
São Felipe D'Oeste         26.481481  31.395833
São Francisco do Guaporé   25.660066  31.638889
São Miguel do Guaporé      25.926346  32.666667
Teixeirópolis              26.031250  31.500000
Theobroma                  25.536082  30.083333
Urupá                      26.688235  31.008929
Vale do Anari              26.096774  34.000000
Vale do Paraíso            25.679012  29.976744
Vilhena                    26.433962  34.152941

### 2. Peso médio dos bebes por sexo que nasceram no dia do seu aniversário por faixas de escolaridade mae
Ex: Você, aluna(o), nasceu no dia 10/01, então você precisa filtrar o conjunto de dados nessa data e calcular o peso médio dos bebês de cada sexo por faixa de escolaridade da mãe.

In [37]:
dict(sinasc_raw['DTNASC'].value_counts())

{'2019-04-10': 116,
 '2019-03-21': 109,
 '2019-09-25': 108,
 '2019-09-02': 105,
 '2019-12-04': 104,
 '2019-04-17': 104,
 '2019-09-16': 103,
 '2019-06-10': 103,
 '2019-04-15': 103,
 '2019-06-19': 103,
 '2019-10-23': 102,
 '2019-04-25': 101,
 '2019-05-27': 100,
 '2019-08-12': 100,
 '2019-09-09': 99,
 '2019-03-11': 99,
 '2019-03-20': 99,
 '2019-05-13': 99,
 '2019-03-18': 98,
 '2019-09-11': 98,
 '2019-04-03': 97,
 '2019-01-16': 97,
 '2019-10-02': 97,
 '2019-03-25': 97,
 '2019-04-12': 97,
 '2019-07-10': 96,
 '2019-09-30': 96,
 '2019-02-28': 96,
 '2019-06-12': 95,
 '2019-11-11': 95,
 '2019-12-18': 94,
 '2019-05-02': 94,
 '2019-02-21': 94,
 '2019-04-02': 93,
 '2019-03-28': 93,
 '2019-07-08': 93,
 '2019-06-26': 92,
 '2019-01-07': 91,
 '2019-11-04': 91,
 '2019-01-21': 91,
 '2019-05-08': 91,
 '2019-11-14': 91,
 '2019-07-03': 90,
 '2019-01-08': 90,
 '2019-12-23': 90,
 '2019-01-15': 90,
 '2019-09-03': 90,
 '2019-08-19': 90,
 '2019-05-15': 90,
 '2019-11-18': 90,
 '2019-10-21': 90,
 '2019-01-14': 90,
 '2019-06-25': 90,
 '2019-05-29': 90,
 '2019-04-22': 90,
 '2019-03-04': 89,
 '2019-09-26': 89,
 '2019-03-15': 89,
 '2019-02-18': 89,
 '2019-02-07': 89,
 '2019-02-19': 89,
 '2019-05-30': 89,
 '2019-05-28': 89,
 '2019-06-05': 89,
 '2019-02-12': 88,
 '2019-05-06': 88,
 '2019-03-14': 87,
 '2019-04-08': 87,
 '2019-11-20': 87,
 '2019-06-03': 87,
 '2019-10-08': 87,
 '2019-03-01': 87,
 '2019-12-02': 87,
 '2019-06-13': 87,
 '2019-01-31': 86,
 '2019-10-18': 86,
 '2019-10-09': 86,
 '2019-11-25': 86,
 '2019-05-14': 86,
 '2019-10-01': 86,
 '2019-02-11': 85,
 '2019-01-17': 85,
 '2019-11-05': 85,
 '2019-05-20': 85,
 '2019-10-16': 85,
 '2019-02-22': 85,
 '2019-08-29': 84,
 '2019-09-18': 84,
 '2019-03-27': 84,
 '2019-08-15': 84,
 '2019-02-14': 84,
 '2019-09-19': 84,
 '2019-12-27': 84,
 '2019-05-01': 84,
 '2019-09-12': 84,
 '2019-03-16': 83,
 '2019-03-06': 83,
 '2019-04-09': 83,
 '2019-06-28': 83,
 '2019-10-24': 83,
 '2019-11-06': 83,
 '2019-02-13': 83,
 '2019-01-23': 83,
 '2019-08-27': 83,
 '2019-02-25': 82,
 '2019-06-18': 82,
 '2019-05-03': 82,
 '2019-04-11': 82,
 '2019-11-07': 82,
 '2019-10-29': 82,
 '2019-05-21': 82,
 '2019-02-08': 82,
 '2019-08-14': 81,
 '2019-09-07': 81,
 '2019-04-18': 81,
 '2019-04-23': 81,
 '2019-04-29': 81,
 '2019-02-27': 81,
 '2019-06-27': 81,
 '2019-04-30': 81,
 '2019-08-08': 81,
 '2019-07-15': 81,
 '2019-10-11': 81,
 '2019-03-19': 81,
 '2019-08-28': 81,
 '2019-08-23': 81,
 '2019-08-05': 80,
 '2019-03-05': 80,
 '2019-03-07': 80,
 '2019-04-04': 80,
 '2019-12-10': 80,
 '2019-12-19': 80,
 '2019-08-07': 79,
 '2019-11-27': 79,
 '2019-09-04': 79,
 '2019-09-17': 79,
 '2019-03-12': 79,
 '2019-03-13': 79,
 '2019-03-17': 79,
 '2019-12-11': 79,
 '2019-03-22': 79,
 '2019-02-26': 79,
 '2019-11-08': 79,
 '2019-01-11': 79,
 '2019-10-31': 78,
 '2019-10-30': 78,
 '2019-07-12': 78,
 '2019-03-29': 78,
 '2019-07-24': 78,
 '2019-08-02': 78,
 '2019-11-13': 78,
 '2019-07-01': 78,
 '2019-09-24': 78,
 '2019-08-26': 78,
 '2019-02-04': 77,
 '2019-08-17': 77,
 '2019-07-09': 77,
 '2019-11-19': 77,
 '2019-01-30': 77,
 '2019-01-03': 77,
 '2019-05-09': 77,
 '2019-10-15': 77,
 '2019-07-22': 77,
 '2019-12-13': 77,
 '2019-04-05': 76,
 '2019-12-05': 76,
 '2019-03-02': 76,
 '2019-12-30': 76,
 '2019-07-30': 76,
 '2019-01-18': 76,
 '2019-08-16': 76,
 '2019-01-28': 76,
 '2019-04-16': 76,
 '2019-09-10': 76,
 '2019-12-17': 76,
 '2019-02-01': 75,
 '2019-07-18': 75,
 '2019-11-12': 75,
 '2019-12-26': 75,
 '2019-06-17': 75,
 '2019-05-17': 75,
 '2019-05-23': 75,
 '2019-01-12': 75,
 '2019-08-06': 74,
 '2019-09-23': 74,
 '2019-02-15': 74,
 '2019-12-09': 74,
 '2019-02-06': 74,
 '2019-12-16': 74,
 '2019-05-07': 74,
 '2019-05-22': 74,
 '2019-07-05': 74,
 '2019-11-01': 74,
 '2019-09-14': 74,
 '2019-07-02': 73,
 '2019-10-03': 73,
 '2019-10-28': 73,
 '2019-05-24': 73,
 '2019-01-04': 73,
 '2019-12-20': 73,
 '2019-05-10': 73,
 '2019-06-07': 73,
 '2019-04-01': 73,
 '2019-11-22': 73,
 '2019-06-06': 73,
 '2019-02-03': 73,
 '2019-06-04': 73,
 '2019-06-24': 72,
 '2019-07-11': 72,
 '2019-09-06': 72,
 '2019-07-26': 72,
 '2019-08-22': 72,
 '2019-07-25': 71,
 '2019-07-29': 71,
 '2019-01-29': 71,
 '2019-09-05': 71,
 '2019-01-05': 71,
 '2019-10-10': 71,
 '2019-02-20': 71,
 '2019-04-26': 71,
 '2019-11-17': 71,
 '2019-04-19': 70,
 '2019-04-14': 70,
 '2019-10-26': 70,
 '2019-03-09': 70,
 '2019-08-01': 70,
 '2019-02-17': 70,
 '2019-12-21': 70,
 '2019-08-25': 70,
 '2019-07-17': 70,
 '2019-11-29': 69,
 '2019-12-06': 69,
 '2019-01-09': 69,
 '2019-05-16': 69,
 '2019-07-31': 69,
 '2019-08-20': 69,
 '2019-04-06': 69,
 '2019-01-24': 69,
 '2019-09-21': 68,
 '2019-02-02': 68,
 '2019-03-24': 68,
 '2019-03-08': 68,
 '2019-01-02': 68,
 '2019-06-21': 68,
 '2019-09-13': 68,
 '2019-09-20': 68,
 '2019-09-28': 68,
 '2019-10-14': 68,
 '2019-05-31': 68,
 '2019-10-07': 67,
 '2019-12-03': 67,
 '2019-03-26': 67,
 '2019-06-20': 67,
 '2019-06-29': 67,
 '2019-08-30': 67,
 '2019-06-14': 67,
 '2019-02-05': 67,
 '2019-10-17': 66,
 '2019-04-24': 66,
 '2019-01-10': 66,
 '2019-09-01': 66,
 '2019-08-09': 66,
 '2019-06-11': 66,
 '2019-07-23': 66,
 '2019-07-19': 66,
 '2019-08-21': 65,
 '2019-09-27': 65,
 '2019-11-09': 65,
 '2019-12-12': 65,
 '2019-06-01': 65,
 '2019-09-15': 65,
 '2019-10-05': 65,
 '2019-03-30': 64,
 '2019-10-04': 64,
 '2019-07-04': 64,
 '2019-01-06': 64,
 '2019-11-28': 64,
 '2019-01-13': 64,
 '2019-01-27': 63,
 '2019-04-21': 63,
 '2019-11-15': 63,
 '2019-07-13': 63,
 '2019-07-16': 62,
 '2019-10-20': 62,
 '2019-05-18': 62,
 '2019-11-23': 62,
 '2019-11-21': 62,
 '2019-10-19': 61,
 '2019-05-11': 61,
 '2019-10-25': 61,
 '2019-05-26': 61,
 '2019-02-10': 61,
 '2019-11-26': 61,
 '2019-04-27': 60,
 '2019-12-24': 60,
 '2019-06-22': 60,
 '2019-04-07': 60,
 '2019-01-19': 59,
 '2019-02-23': 59,
 '2019-12-28': 59,
 '2019-07-06': 58,
 '2019-01-22': 58,
 '2019-03-10': 58,
 '2019-09-22': 58,
 '2019-10-22': 57,
 '2019-08-13': 57,
 '2019-05-12': 57,
 '2019-04-13': 57,
 '2019-06-15': 57,
 '2019-05-25': 56,
 '2019-12-14': 56,
 '2019-10-13': 56,
 '2019-07-21': 56,
 '2019-11-30': 55,
 '2019-01-26': 55,
 '2019-12-07': 55,
 '2019-05-19': 55,
 '2019-07-27': 55,
 '2019-05-04': 55,
 '2019-08-31': 55,
 '2019-02-24': 54,
 '2019-08-10': 54,
 '2019-06-02': 54,
 '2019-08-11': 54,
 '2019-07-14': 54,
 '2019-09-08': 54,
 '2019-11-16': 54,
 '2019-03-03': 54,
 '2019-06-08': 53,
 '2019-11-02': 53,
 '2019-11-24': 53,
 '2019-10-27': 53,
 '2019-10-06': 53,
 '2019-09-29': 53,
 '2019-04-20': 53,
 '2019-07-07': 52,
 '2019-01-20': 52,
 '2019-02-16': 52,
 '2019-12-01': 52,
 '2019-04-28': 52,
 '2019-08-24': 52,
 '2019-10-12': 52,
 '2019-05-05': 51,
 '2019-11-10': 51,
 '2019-08-03': 51,
 '2019-12-31': 51,
 '2019-01-25': 50,
 '2019-03-23': 50,
 '2019-03-31': 49,
 '2019-12-08': 49,
 '2019-06-30': 49,
 '2019-06-23': 49,
 '2019-07-20': 49,
 '2019-06-16': 48,
 '2019-12-29': 48,
 '2019-01-01': 48,
 '2019-06-09': 48,
 '2019-12-22': 47,
 '2019-08-18': 47,
 '2019-12-15': 45,
 '2019-12-25': 44,
 '2019-02-09': 44,
 '2019-07-28': 44,
 '2019-08-04': 43,
 '2019-11-03': 40}

In [39]:
sinasc_raw[sinasc_raw['DTNASC']=='2019-12-30'].groupby('ESCMAE').agg({'PESO':'mean'})

                        PESO
ESCMAE
1 a 3 anos       3532.000000
12 anos ou mais  3383.375000
4 a 7 anos       3186.142857
8 a 11 anos      3218.657895

### 3. Qual o municipio que nasceu menos bebe em 2019?
    - qual a idade media, maxima, minima das maes nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [61]:
sinasc_raw['munResNome'].value_counts().sort_values(ascending=True)

munResNome
Município ignorado - RO         1
Castanheiras                   32
Pimenteiras do Oeste           40
Primavera de Rondônia          43
Parecis                        44
Rio Crespo                     50
São Felipe D'Oeste             54
Teixeirópolis                  64
Cacaulândia                    75
Cabixi                         80
Vale do Paraíso                81
Ministro Andreazza             84
Vale do Anari                  93
Theobroma                      97
Novo Horizonte do Oeste        98
Santa Luzia D'Oeste            99
Nova União                    104
Itapuã do Oeste               109
Governador Jorge Teixeira     112
Corumbiara                    127
Alto Alegre dos Parecis       154
Chupinguaia                   162
Mirante da Serra              164
Campo Novo de Rondônia        166
Seringueiras                  168
Urupá                         170
Monte Negro                   199
Alvorada D'Oeste              205
Cujubim                       205
Colorado do Oeste             214
Alto Paraíso                  226
Costa Marques                 233
Cerejeiras                    237
Nova Brasilândia D'Oeste      261
São Francisco do Guaporé      303
Presidente Médici             304
Candeias do Jamari            337
São Miguel do Guaporé         353
Alta Floresta D'Oeste         367
Nova Mamoré                   432
Espigão D'Oeste               450
Machadinho D'Oeste            500
Buritis                       583
Pimenta Bueno                 616
Ouro Preto do Oeste           631
Guajará-Mirim                 781
Jaru                          881
Rolim de Moura                927
Cacoal                       1374
Vilhena                      1590
Ariquemes                    1729
Ji-Paraná                    2182
Porto Velho                  8437
Name: count, dtype: int64

In [67]:
sinasc_raw[sinasc_raw['munResNome']=='Castanheiras'].groupby('munResNome').agg({'IDADEMAE': ['mean', 'max', 'min'], 'IDADEPAI': ['mean', 'max', 'min']})

              IDADEMAE           IDADEPAI
                  mean max min       mean   max   min
munResNome
Castanheiras  27.28125  39  17  30.392857  43.0  17.0

### 4. Qual o municipio que nasceu mais bebe no mês de março?
    - qual a quantidade de filhos vivos media, maxima, minima nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [69]:
sinasc_raw['DTNASC']

0        2019-02-19
1        2019-02-21
2        2019-02-25
3        2019-03-20
4        2019-03-23
            ...
27023    2019-12-13
27024    2019-10-04
27025    2019-08-02
27026    2019-12-23
27027    2019-12-27
Name: DTNASC, Length: 27028, dtype: object

In [147]:
sinasc_raw['DTNASC'] = pd.to_datetime(sinasc_raw['DTNASC'], errors='coerce')
marco_df = sinasc_raw[sinasc_raw['DTNASC'].dt.strftime('%m') == '03']

In [149]:
marco_df['munResNome'].value_counts()

munResNome
Porto Velho                  744
Ji-Paraná                    188
Vilhena                      148
Ariquemes                    141
Cacoal                       133
Jaru                          80
Guajará-Mirim                 75
Rolim de Moura                69
Ouro Preto do Oeste           67
Pimenta Bueno                 62
Buritis                       59
Nova Mamoré                   53
Machadinho D'Oeste            44
Espigão D'Oeste               44
São Miguel do Guaporé         41
Candeias do Jamari            33
São Francisco do Guaporé      31
Alta Floresta D'Oeste         31
Presidente Médici             29
Costa Marques                 24
Alto Paraíso                  22
Alvorada D'Oeste              22
Monte Negro                   20
Nova Brasilândia D'Oeste      20
Seringueiras                  19
Colorado do Oeste             19
Chupinguaia                   18
Cujubim                       17
Cerejeiras                    16
Urupá                         14
Vale do Paraíso               13
Campo Novo de Rondônia        13
Corumbiara                    12
Vale do Anari                 11
Governador Jorge Teixeira     10
Alto Alegre dos Parecis       10
Cacaulândia                   10
Mirante da Serra               9
Rio Crespo                     9
Theobroma                      8
Itapuã do Oeste                8
Santa Luzia D'Oeste            7
Nova União                     7
Pimenteiras do Oeste           6
Cabixi                         6
Parecis                        6
Ministro Andreazza             6
Primavera de Rondônia          5
Novo Horizonte do Oeste        5
São Felipe D'Oeste             5
Castanheiras                   4
Teixeirópolis                  3
Name: count, dtype: int64

In [155]:
sinasc_raw[sinasc_raw['munResNome']=='Porto Velho'].groupby('munResNome').agg({'QTDFILVIVO':['sum','mean','max','min'], 'IDADEMAE':['mean','max','min'],'IDADEPAI':['mean','max','min']})

            QTDFILVIVO                       IDADEMAE           IDADEPAI  \
                   sum      mean   max  min      mean max min       mean
munResNome
Porto Velho     8543.0  1.167236  12.0  0.0  26.31267  47  12  32.352679


              max   min
munResNome
Porto Velho  65.0  16.0

### Analise as respostas encontradas, tire algum insight delas, conte pra gente algo encontrado nos dados. Algo que você julgue relevante e novo pra você.

In [ ]:
#Um dos primeiros insight é que na capital é onde ocorre o maior número de nascimentos. Outra informação é que em média o pai
#da criança é mais velho que a mãe. E no mês de março aconteceu que as mães com baixa escolaridade tiveram filhos mais pesados do
# que as mães com elevada escolaridade.

Exemplo:
- Ah, descobri que a idade mediana das mulheres que deram a luz no ano de 2019 dos municipios x é maior que y.

In [6]:
sinasc_raw.dtypes

ORIGEM          int64
CODESTAB      float64
CODMUNNASC      int64
LOCNASC         int64
IDADEMAE        int64
               ...
munResUf       object
munResLat     float64
munResLon     float64
munResAlt     float64
munResArea    float64
Length: 69, dtype: object

In [7]:
sinasc_raw.select_dtypes(exclude=['int64','float64'])

,ESCMAE,GESTACAO,GRAVIDEZ,PARTO,DTNASC,SEXO,RACACOR,DTCADASTRO,CODANOMAL,VERSAOSIST,DTRECEBIM,munResStatus,munResTipo,munResNome,munResUf
0,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-02-19,Masculino,Branca,2019-03-08,NaN,3.2.01,2019-03-08,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
1,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-02-21,Feminino,Branca,2019-03-08,NaN,3.2.01,2019-03-08,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
2,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-02-25,Feminino,Branca,2019-03-08,NaN,3.2.01,2019-03-08,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
3,12 anos ou mais,37 a 41 semanas,Única,Cesáreo,2019-03-20,Feminino,Parda,2019-04-03,NaN,3.2.01,2019-04-09,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia
4,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-03-23,Feminino,Parda,2019-04-03,NaN,3.2.01,2019-04-09,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27023,12 anos ou mais,32 a 36 semanas,Única,Cesáreo,2019-12-13,Masculino,Branca,2020-09-28,NaN,3.2.01,2020-10-13,ATIVO,MUNIC,Vilhena,Rondônia
27024,8 a 11 anos,37 a 41 semanas,Única,Vaginal,2019-10-04,Masculino,Branca,2019-10-16,NaN,3.2.01,2019-10-21,ATIVO,MUNIC,Chupinguaia,Rondônia
27025,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-08-02,Masculino,Parda,2019-08-07,NaN,3.2.00,2019-08-07,ATIVO,MUNIC,Vilhena,Rondônia
27026,8 a 11 anos,32 a 36 semanas,Única,Vaginal,2019-12-23,Masculino,Parda,2020-01-07,NaN,3.2.00,2020-01-07,ATIVO,MUNIC,Vilhena,Rondônia
27027,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-12-27,Masculino,Parda,2020-10-15,NaN,3.2.01,2020-10-16,ATIVO,MUNIC,Novo Horizonte do Oeste,Rondônia

In [4]:
sinasc_raw.columns

Index(['ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE', 'ESTCIVMAE',
       'ESCMAE', 'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'CODMUNRES',
       'GESTACAO', 'GRAVIDEZ', 'PARTO', 'CONSULTAS', 'DTNASC', 'HORANASC',
       'SEXO', 'APGAR1', 'APGAR5', 'RACACOR', 'PESO', 'IDANOMAL', 'DTCADASTRO',
       'CODANOMAL', 'NUMEROLOTE', 'VERSAOSIST', 'DTRECEBIM', 'DIFDATA',
       'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU', 'ESCMAE2010',
       'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT', 'QTDPARTNOR',
       'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC', 'TPMETESTIM',
       'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART', 'STCESPARTO',
       'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC', 'ESCMAEAGR1',
       'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON', 'PARIDADE',
       'KOTELCHUCK', 'CONTADOR', 'munResStatus', 'munResTipo', 'munResNome',
       'munResUf', 'munResLat', 'munResLon', 'munResAlt', 'munResArea'],
      dtype='object')